apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-deployment
  namespace: wanderlust

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:

      - name: frontend

        image: mujtabas/wanderlust-frontend:v1

        imagePullPolicy: Always

        ports:
        - containerPort: 5173

        env:
        - name: VITE_API_PATH
          valueFrom:
            configMapKeyRef:
              name: wanderlust-config
              key: VITE_API_PATH

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "300m"
            memory: "256Mi"

---

apiVersion: v1
kind: Service

metadata:
  name: frontend-service
  namespace: wanderlust

spec:

  selector:
    app: frontend

  type: NodePort

  ports:
  - port: 5173
    targetPort: 5173
    nodePort: 31000
